apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - image: char2pie/reverseproxy
    name: reverseproxy
    # when the container is re-scheduled, always pull the updated image from registry
    imagePullPolicy: Always      
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always

  # run this file to start one pod
  # $ kubectl apply -f pod.yaml